---
title: "Rworksheet_Garcia#3b"
output: html_document
---
```{r}

#1.a

# Create the data frame
respondents <- c(1:20)
sex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
fathers_occupation <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
persons_at_home <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
siblings_at_school <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
types_of_houses <- c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

data <- data.frame(respondents, sex, fathers_occupation, persons_at_home, siblings_at_school, types_of_houses)
data

```
#1.b
```{r}
# Get the structure of the data
str(data)

# Get the summary of the data
summary(data)
```

#1.c
```{r}
mean_siblings <- mean(respondents$Siblings_at_School)
mean_siblings

```


#1.d
```{r}
respondents[1:2, ]

```

#1.e
```{r}
respondents[c(3,5), c(2,4)]

```

#1.f
```{r}
types_houses <- respondents$Types_of_Houses
types_houses
```

#1.g
```{r}
subset(respondents, Sex == 1 & Fathers_Occupation == 1)
```

#1.h
```{r}
subset(respondents, Sex == 2 & Siblings_at_School >= 5)
```

#2.a
```{r}
# Create an empty data frame
df = data.frame(
  Ints = integer(),
  Doubles = double(),
  Characters = character(),
  Logicals = logical(),
  Factors = factor(),
  stringsAsFactors = FALSE
)

print("Structure of the empty dataframe:")
print(str(df))
```

#3.a
```{r}
# Create the data frame
HouseholdData <- data.frame(
  Respondents = 1:10,
  Sex = c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male"),
  Fathers_Occupation = c(1,2,3,3,1,2,2,3,1,3),
  Persons_at_Home = c(5,7,3,8,6,4,4,2,11,6),
  Siblings_at_School = c(2,3,0,5,2,3,1,2,6,2),
  Types_of_Houses = c("Wood","Concrete","Concrete","Wood","Semi-concrete",
                      "Semi-concrete","Wood","Semi-concrete","Semi-concrete","Concrete")
)

# Save to CSV
write.csv(HouseholdData, "HouseholdData.csv", row.names = FALSE)

```

#3.b
```{r}
house_data$Sex <- factor(house_data$Sex, levels = c("Male", "Female"), labels = c(1, 2))
house_data$Sex
```

#3.c
```{r}
house_data$Types_of_Houses <- factor(
  house_data$Types_of_Houses,
  levels = c("Wood", "Concrete", "Semi-concrete"),
  labels = c(1, 2, 3)
)
house_data$Types_of_Houses
```

#3.d
```{r}
house_data$Fathers_Occupation <- factor(
  house_data$Fathers_Occupation,
  levels = c(1, 2, 3),
  labels = c("Farmer", "Driver", "Others")
)
house_data$Fathers_Occupation
```

#3.e
```{r}
subset(house_data, Sex == 2 & Fathers_Occupation == "Driver")

```

#3.f
```{r}
subset(house_data, Siblings_at_School >= 5)

```

#4.interpret the graph
```{r}
Date <- c(
  "July 14", "July 14", "July 14",
  "July 15", "July 15", "July 15",
  "July 17", "July 17", "July 17",
  "July 18", "July 18", "July 18",
  "July 20", "July 20", "July 20",
  "July 21", "July 21", "July 21"
)
Sentiment <- rep(c("Negative", "Neutral", "Positive"), times = 6)
Count <- c(
  2400, 1600, 1700,
  3800, 2900, 3200,
  3300, 1700, 2500,
  3300, 2000, 2600,
  2200, 1400, 1600,
  3700, 2800, 3400
)
sentiment_data <- data.frame(Date, Sentiment, Count)
sentiment_data
```















