---
title: 'Lab Exercise #1'
author: "Carol D. Garcia"
date: "2025-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# 1. Create a vector using : operator
x1 <- -5:5
print(x1) 
# [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

x2 <- 1:7
print(x2)  # Sequence from 1 to 7
#[1] 1 2 3 4 5 6 7
```

```{r}
# 2. Create a vector using seq() function
x3 <- seq(1, 3, by = 0.2)
print(x3) 
#[1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0
```

```{r}
# 3. Accessing elements in a vector (worker ages)
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
          22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 
          43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 38, 
          41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)

# A. Access 3rd element
print(ages[3])  
#[1] 22

# B. Access 2nd and 4th element
print(ages[c(2, 4)]) 
#[1] 28 36

# C. Access all but the 1st element
print(ages[-1])  
#[1] 28 22 36 27 18 52 39 42 29 35 31 27 22 37 34 19 20 57 49 50 37 46 25 17 37 43 53 41 51 35 24 33 41
#[34] 53 40 18 44 38 41 48 27 39 19 30 61 54 58 26 18
```

```{r}
# 4. Named vector
x4 <- c("first" = 3, "second" = 0, "third" = 9)
print(names(x4))  
#[1] "first"  "second" "third" 
print(x4[c("first", "third")]) 
#first third 
#    3     9 
```

```{r}
# 5. Modify vector
x5 <- -3:2
x5[2] <- 0  
print(x5) 
#[1] -3  0 -1  0  1  2
```

```{r}
# 6. Data frame for Mr. Cruz's fuel purchases
months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

#A. data frame
fuel_data <- data.frame(Month = months, Price_per_liter = price_per_liter, Purchase_quantity = purchase_quantity)
print(fuel_data)  

#B. Average fuel expenditure
average_expenditure <- weighted.mean(price_per_liter, purchase_quantity)
print(average_expenditure)  
#[1] 59.2625
```

```{r}
# 7. Rivers data summary
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data) 
#[1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000
```

```{r}
# 8. Forbes Celebrity Rankings (Example code based on a hypothetical table)
# You would need to replace these values with actual celebrity names and earnings.
#A.
celebrity_names <- c("Celebrity 1", "Celebrity 2", "Celebrity 3", "J.K. Rowling", "Celebrity 5")
pay <- c(100, 90, 85, 80, 75) 
ranking <- c(1, 2, 3, 4, 5) 
#B.
celebrity_data <- data.frame(Name = celebrity_names, Pay = pay, Ranking = ranking)
print(celebrity_data) 
#C.
# Modify J.K. Rowling's ranking and pay
celebrity_data[celebrity_data$Name == "J.K. Rowling", c("Ranking", "Pay")] <- c(15, 90)
print(celebrity_data)  
``` 