---
title: "Rworkesheet_Garcia#3a"
author: "Carol D. Garcia"
date: "2025-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Part 1
#a.
LETTERS[1:11]

#b
LETTERS[seq(1,25,by=2)]

#c.
LETTERS[c(1,5,9,15,21)]

#d.
last5 <- LETTERS[22:26]

#e.
between <- LETTERS[15:24]

```
```{r}
#Part 2

#a.
city <- c("Tugue-garao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")

#b.
temp <- c(42,39,34,34,30,27)

#c.
citytemp <- data.frame(city,temp)

#d.
names(citytemp)[1] <- "City"
names(citytemp)[2] <- "Temperature"
citytemp

#e.
str(citytemp)
#the data frame containing six cities with their corresponding temperature

#f.
#the content of row 3 and 4 is iloilo and tacloban,they have the same temperature

#g.
print(citytemp[1,])
print(citytemp[6,])
```
```{r}
#1a.
matrix(c(5,6,7,4,3,2,1,2,3,7,8,9),nrow = 2)

matrix(data = c(3,4,5,6,7,8),3,2)


diag(1,nrow = 6,ncol = 5)

diag(6)
```
```{r}
#2a.
my_matrix <- matrix(c(1:8, 11:14),nrow =3,ncol = 4)

#2b.
my_matrix * 2

#2c.
my_matrix[2,]

#2d.
my_matrix[1:2, 3:4]

#2e.
my_matrix[3, 2:3]

#2f.
my_matrix[, 4]

#2g.
dimnames(my_matrix) <- list(c("isa","dalawa","tatlo"))
                            #Rows names (3 rows)c ("uno","dos","tres","quatro") # Colums names (4 columns) )
                            
                            
#2h.
dim(my_matrix) <- c(6,2)
my_matrix

```
```{r}
#array

#3a.
# Original values
values <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)

# Repeat each value twice
rep_values <- rep(values, each = 2)

# Create a 3D array with 2 rows, 4 columns, and 3 dimensions
array_dta <- array(rep_values, dim = c(2, 4, 3))
array_dta

#3b.
dim(array_dta)

#3c. 
# Adding names
dimnames(array_dta) <- list(
  rows = c("a", "b"),   # lowercase row names
  columns = c("A", "B", "C", "D"),   # uppercase column names
  dimension = c("1st-Dimensional Array", 
                "2nd-Dimensional Array", 
                "3rd-Dimensional Array")  # layer names
)

array_dta
```
